theme: jekyll-theme-slate
title:  Rothrock Chiropractic & Rehabilitation, Chiropractors serving State College, Pa and Centre County
tagline: Rothrock Chiropractic & Rehabilitation, State College Area Chiropractors
description: Rothrock Chiropractic & Rehabiliation is your local chiropractor in State College, PA. We are located in Center for Wellbeing at 123 Mount Nittany Rd, Lemont, PA. We are happy to serve patients from Lemont, State College, Boalsburg, Nittany Valley, and the Centre County region. Call us today at (814) 441-5532 for an appointment.
logo: '/images/Rothrock-logo.png'
canonical_url: 'https://rothrockchiro.com'
markdown: kramdown

# baseurl: /rothrockchiropractic.com

plugins:
- jekyll-seo-tag
- jekyll-sitemap
